Repository SAP/cloud-sdk-js, pull requests merged in 2020-09, with the labels that each got.

#442 docs: Odata v4 overview
  docs/js/features/odata/execute-odata-request.mdx
  docs/js/features/odata/generate-odata-client.mdx
  docs/js/features/odata/odata-v2-client.mdx
  docs/js/features/odata/odata-v4-client.mdx
  docs/js/features/odata/overview.mdx
  sidebars.js
Labels: documentation

#420 Expand section on destination mocking
  docs/java/features/connectivity/destinations.md
Labels: documentation

#240 Pull request template for docs
  .github/PULL_REQUEST_TEMPLATE_DOCS.md
Labels: documentation

#436 Filter doc
  docs/js/features/odata/odata-v2-client.mdx
  docs/js/features/odata/odata-v4-client.mdx
Labels: documentation

#461 doc: multiple changesets
  docs/js/features/odata/odata-v2-client.mdx
Labels: documentation

#462 doc: Update docusaurus
  docs/support/support.md
  package-lock.json
  package.json
Labels: documentation

#463 doc: Add link to latest api doc version
  docs/js/api.mdx
  docs/js/extension-model.md
  docs/js/features/connectivity/proxy.md
  docs/js/features/odata/overview.mdx
  docs/js/redirect-api-reference-js-ts.mdx
  docs/js/release-notes.md
  sidebars.js
  src/pages/api/index.js
  src/pages/api/latest.mdx
  src/sap/sdk-js/ApiReleaseList/index.js
Labels: documentation

#451 Doc: Business application studio
  docs/js/guides/bas-external-system.md
  sidebars.js
  static/img/cf-connect-button.jpg
  static/img/cloud-connector.graffle
  static/img/cloud-connector.png
Labels: documentation

#468 [docs] release notes for v3.28.1
  docs/java/release-notes.md
Labels: documentation

#473 OData v4 client for JS is no longer experimental
  docs/js/features/odata/odata-v4-client.mdx
Labels: documentation

#470 Remove absolute link
  docs/js/features/odata/odata-v4-client.mdx
Labels: documentation

#452 Doc: Generic Http Client
  docs/js/features/connectivity/on-premise.md
  docs/js/features/connectivity/proxy.md
  docs/js/features/odata/generic-http-client.md
  sidebars.js
  src/css/custom.css
  static/img/odata-client-layers.graffle
  static/img/odata-client-layers.png
  static/img/on-premise-connectivity.graffle
  static/img/on-premise-connectivity.png
Labels: documentation

#475 [doc] Use pathname instead of full url
  docs/js/features/connectivity/destination.md
  docs/js/features/odata/generic-http-client.md
Labels: documentation

#460 [docs] upcoming dates for 2020
  docs/community/community-call.md
Labels: documentation

#479 Fix typo in docs
  docs/java/features/connectivity/destinations.mdx
Labels: documentation

#490 Add chapter about websocket rfc client
  docs/java/features/bapi-and-rfc/overview.mdx
Labels: documentation

#493 Add note about supported data types
  docs/java/features/odata/generate-client.mdx
Labels: documentation

#486 [Java] Update Docu on ETag Handling
  docs/java/features/odata/type-safe-client-odata-v2.mdx
Labels: documentation, don't merge

#483 PR #2 for Currency Conversion Docu
  docs/java/features/extensions/extension-library/curconv/currency-conversion.mdx
Labels: documentation

#501 SDK JS docs: v4 not in beta anymore
  docs/js/features/odata/overview.mdx
Labels: documentation

#491 [Chore] Add as child documentation
  docs/js/features/odata/odata-v2-client.mdx
  package-lock.json
Labels: documentation

#497 [Doc] Subqueries in expand
  docs/js/features/odata/odata-v4-client.mdx
  docs/overview/what-is-new.mdx
  package-lock.json
Labels: documentation

#503 [Doc]: function imports
  docs/js/features/odata/odata-v2-client.mdx
Labels: documentation

#510 [Fix] Response parsing of 1:N relations in C4C
  CHANGELOG.md
  packages/core/src/odata/common/entity-deserializer.ts
  packages/core/src/odata/v2/entity-deserializer.ts
  packages/core/src/odata/v2/extract-data-from-one-to-many-link.ts
  packages/core/src/odata/v2/request-builder/response-data-accessor.ts
  packages/core/src/odata/v4/entity-deserializer.ts
  packages/core/src/odata/v4/extract-data-from-one-to-many-link.ts
  packages/core/src/odata/v4/request-builder/response-data-accessor.ts
  packages/core/test/odata/v2/entity-deserializer.spec.ts
  packages/core/test/odata/v2/response-data-accessor.spec.ts
  packages/core/test/odata/v4/response-data-accessor.spec.ts
Labels: bug

#511 A note about BOM versioning approach for SDK dependencies
  docs/java/features/extensions/extension-library/curconv/currency-conversion.mdx
Labels: documentation

#485 Updated JCo doc to new buildpack features
  docs/java/features/bapi-and-rfc/overview.mdx
Labels: documentation

#469 Update docu about OData client
  docs/java/features/odata/type-safe-client-odata-v2.mdx
Labels: documentation

#512 Batch example
  docs/java/features/odata/type-safe-client-odata-v2.mdx
Labels: documentation

#515 Release notes 3.29.1. Release blog and javadoc TBD
  docs/java/release-notes.mdx
Labels: documentation

#533 Add docu about batch
  docs/java/features/odata/type-safe-client-odata-v2.mdx
  docs/java/features/odata/type-safe-client-odata-v4.mdx
Labels: documentation
