Repository SAP/cloud-sdk-js, pull requests merged in 2020-07, with the labels that each got.

#231 Update WF API method name
  docs/java/features/rest/clients/scp-workflow-rest-api.md
Labels: documentation

#230 Update Java troubleshooting docs
  docs/java/troubleshooting.md
Labels: documentation

#229 Add section about local deployment
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#214 Java resilience documentation
  docs/java/features/odata/use-vdm.md
  docs/java/features/resilience/resilience.md
  sidebars.js
Labels: documentation

#236 Fix typo on BAPI documentation page
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#234 Update title and links on JS API reference
  docs/js/api-reference.md
Labels: documentation

#237 updated/improved JCo related doc
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#223 Update Java Docs Structure
  docs/java/api-reference.md
  docs/java/features/odata/generate-client.md
  docs/java/guides/increase-log-level.md
  docs/java/introduction.md
  docs/java/release-notes.md
  docs/overview/about.md
  docusaurus.config.js
  sidebars.js
Labels: documentation

#251 Release notes java
  docs/java/api-reference.md
  docs/java/release-notes.md
  sidebars.js
Labels: documentation

#253 Refine local deployment section of BAPI documentation
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#255 Revert "Add section about destinations env var (#253)"
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#256 Guide dependency problems
  docs/java/guides/dependencies.md
  docs/java/troubleshooting.md
  sidebars.js
Labels: documentation

#260 Unify logging guides
  docs/java/guides/increase-log-level.md
  docs/java/guides/logging-overview.md
  sidebars.js
Labels: documentation

#259 Add a note about overriding dependencies
  docs/java/guides/dependencies.md
Labels: documentation

#245 JS Documentation: Batch request
  docs/js/features/odata/use-generated-client.md
Labels: documentation

#228 Documentation: JS added expand, and deep create / update
  docs/js/features/odata/use-generated-client.md
Labels: documentation

#226 Documentation: JS Getting started
  docs/js/getting-started.md
Labels: documentation

#274 Refine plugin configuration for BAPI local deployment
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#272 Fix typos in JS SDK: destination documentation
  docs/js/features/connectivity/destination.md
  sidebars.js
Labels: documentation

#296 chore: Fix lodash dependencies
  package-lock.json
  packages/generator/package-lock.json
  test-packages/integration-tests/package-lock.json
  test-packages/integration-tests/package.json
Labels: dependencies

#297 Java release notes: clarify wording on version 2
  docs/java/release-notes.md
Labels: documentation

#304 A hint on performance for troubleshooting
  docs/java/troubleshooting.md
Labels: documentation

#290 Refine BAPI/RFC docu for local deployment
  docs/java/features/bapi-and-rfc/overview.md
Labels: documentation

#265 [Java] [OData VDM] Correct & update code example for OData 4.0 API
  docs/java/features/odata/use-vdm.md
Labels: documentation

#327 Update link to JS release notes
  docusaurus.config.js
Labels: documentation

#307 Extension model
  docs/js/extension-model.md
Labels: contribution, documentation

#325 Documentation for improved OData VDM implementation
  docs/java/features/odata/overview.md
  docs/java/features/odata/use-vdm.md
Labels: documentation
