Repository SAP/cloud-sdk-js, pull requests merged in 2020-05, with the labels that each got.

#112 chore: use new api doc link for the npm readme
  README.md
  packages/core/README.md
  packages/generator/README.md
  packages/test-util/README.md
  packages/util/README.md
Labels: please merge, please review

#103 odata V4 collection type + dummy vdm
  packages/core/src/entity-deserializer.ts
  packages/core/src/entity-serializer.ts
  packages/core/src/selectable/collection-field.ts
  packages/core/src/selectable/index.ts
  packages/core/src/selectable/selectable.ts
  packages/core/test/entity-deserializer.spec.ts
  packages/core/test/entity-serializer.spec.ts
  packages/core/test/test-util/test-services/test-service-odata-v4/LocationType.ts
  packages/core/test/test-util/test-services/test-service-odata-v4/Person.ts
  packages/core/test/test-util/test-services/test-service-odata-v4/PersonRequestBuilder.ts
  packages/core/test/test-util/test-services/test-service-odata-v4/index.ts
  test-packages/test-services/srv/dummy-trip-service/LocationType.ts
  test-packages/test-services/srv/dummy-trip-service/Person.ts
  test-packages/test-services/srv/dummy-trip-service/PersonRequestBuilder.ts
Labels: please merge, please review

#110 Split commit into 2 files, improve naming, fix typos
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: documentation, please merge, please review

#107 Fix: Improve logging on edmx generation and file creation
  CHANGELOG.md
  packages/generator/src/generator-cli.ts
  packages/generator/src/generator.ts
Labels: please merge, please review

#117 Add .vscode to gitignore
  .gitignore
Labels: documentation, please merge, please review

#109 Use odata
  docs/java/features/connectivity/destinations.md
  docs/java/features/odata/use-vdm.md
  sidebars.js
Labels: documentation, please review

#123 Fix xml syntax highlighting
  docs/java/features/odata/generate-client.md
Labels: documentation, please merge, please review

#111 Adding Tips&tricks section for Java, logging tip
  docs/java/tips-and-tricks/logging.md
  sidebars.js
Labels: documentation, please merge, please review

#121 Add Documentation for SCP Workflow REST API Client Lib
  .gitignore
  docs/java/features/rest/clients/blockchain.md
  docs/java/features/rest/clients/core-services.md
  docs/java/features/rest/clients/currency-conversion.md
  docs/java/features/rest/clients/scp-workflow-rest-api.md
  docs/java/features/rest/clients/workflow-api.md
  docs/java/features/rest/overview.md
  docs/java/features/rest/sdk-as-a-service.md
  sidebars.js
Labels: documentation, please merge, please review

#115 First shot at Java logging documentation
  docs/java/guides/logging-overview.md
  sidebars.js
Labels: documentation, please merge, please review

#133 Synchronise Tab Choices in OData Usage Documentation
  docs/java/features/odata/use-vdm.md
Labels: documentation

#129 Add FAQ. Update API reference for 3.19.1, Update sidebar
  docs/java/api-reference.md
  docs/java/faq.md
  sidebars.js
Labels: documentation

#132 Add list of parameters for OData Generator
  docs/java/features/odata/generate-client.md
Labels: documentation, help wanted

#141 Create initial documentation on the ThreadContext
  docs/java/features/multi-tenancy/thread-context.md
  docs/java/features/odata/generate-client.md
  sidebars.js
Labels: documentation, help wanted

#142 Fix typo in Thread Context docu
  docs/java/features/multi-tenancy/thread-context.md
Labels: documentation

#134 Add forEntity reference to the documentation (java)
  docs/java/features/odata/generate-client.md
  docs/java/features/odata/use-vdm.md
Labels: documentation

#154 Point to edit URL
  docs/js/introduction.md
  docusaurus.config.js
Labels: documentation

#153 Revise docs on ci/cd
  docs/devops/getting-started.md
Labels: documentation

#155 Remove all custom edit URLs
  docs/core/cf.md
  docs/core/cloud-native.md
  docs/core/odata.md
  docs/core/open-api.md
  docs/core/pipeline.md
  docs/core/router.md
  docs/core/tenant.md
  docs/core/vdm.md
  docs/core/xsuaa.md
  docs/dzen/getting-started.md
  docs/dzen/how-to-write-docs.md
  docs/faq/faq.md
  docs/java/features/archetype.md
  docs/java/features/cli.md
  docs/java/features/multi-tenancy/thread-context.md
  docs/java/features/rest/overview.md
  docs/java/guides/cf-cli.md
  docs/java/guides/cf-deploy.md
  docs/java/guides/linux-how-to.md
  docs/overview/about.md
  docs/partners/c4re.md
  docs/related-projects/c4re.md
  docs/related-projects/s4hana.md
  docs/related-projects/xsuaa.md
Labels: documentation

#158 Fix wording and typos on main page
  src/pages/index.js
Labels: documentation

#156 Replace term VDM with typed OData client
  docs/java/features/odata/generate-client.md
  docs/java/features/odata/overview.md
  docs/java/features/odata/use-vdm.md
Labels: documentation

#160 Remove further occurrences of term VDM
  docs/java/features/odata/generate-client.md
  docs/java/features/odata/use-vdm.md
  docs/overview/key-features.md
Labels: documentation

#161 Adding Eslint, minor fixes to JS files
  .eslintrc.js
  package-lock.json
  package.json
  src/pages/index.js
  src/sap/utils/index.js
Labels: documentation

#162 Update links, fix wording in headers and sidebar
  docs/java/features/odata/generate-client.md
  docs/java/features/odata/overview.md
  docs/java/features/odata/use-vdm.md
  sidebars.js
Labels: documentation

#163 Overview section for REST and a bit of restructuring on sidebar
  docs/java/features/rest/clients/scp-workflow-rest-api.md
  docs/java/features/rest/overview.md
  sidebars.js
Labels: documentation
